# Generated by Django 3.1.4 on 2021-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),

            ],
            options={
                'verbose_name': 'Игроки',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=20, verbose_name='Винрейт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('commands', models.ManyToManyField(related_name='name_commands', to='basketball.Player', verbose_name='игроки')),
            ],
            options={
                'verbose_name': 'Игроки',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
