# Generated by Django 3.1.4 on 2021-01-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вес'),
        ),
    ]
