# Generated by Django 3.1.4 on 2021-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_auto_20210103_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во очков'),
        ),
    ]
