# Generated by Django 3.1.4 on 2021-01-14 17:31

import basketball.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_player_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='commands',
            name='tagline',
        ),
        migrations.AddField(
            model_name='commands',
            name='photo',
            field=models.ImageField(default='commands/default.jpg', upload_to=basketball.models.commands_photo, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='players/default.jpeg', upload_to=basketball.models.player_photo, verbose_name='Фото'),
        ),
    ]
